<table class="table">
    <thead>
    <tr>
        <th width="30">
            <input type="checkbox"
                   id="customCheckAll"
                   title="Отметить/снять все"
                   value="Y"
                   name="id[]" class="custom-control-label-all">
            <label for="customCheckAll"></label>
        </th>
        <th width="50">ID</th>
        <th>Ключ</th>
        <th>Значение</th>
        <th>Комментарий</th>
        <th>Модуль</th>
        <th>Действие</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($vars['list'] as $row) { ?>
        <tr>
            <td>
                <input type="checkbox" value="<?php echo $row['id'] ?>"
                       id="customCheck<?php echo $row['id'] ?>"
                       name="id[]" class="custom-control-label">
                <label for="customCheck<?php echo $row['id'] ?>"></label>
            </td>
            <td><?php echo $row['id'] ?>
                <input type="hidden" value="<?php echo $row['id'] ?>" name="save_id[]"/>
            </td>
            <td>
                <input type="text" value="<?php echo $row['key'] ?>" name="key[]" class="form-control">
            </td>
            <td>
                <textarea name="value[]" class="form-textarea no-size"><?php echo $row['value'] ?></textarea>
            </td>
            <td>
                <textarea name="comment[]" class="form-textarea no-size"><?php echo $row['comment'] ?></textarea>
            </td>
            <td>
                <select class="custom-select" name="modules_id[]">
                    <option value="">...</option>
                    <?php foreach ($vars['modules'] as $row2) { ?>
                        <option value="<?php echo $row2['id'] ?>"
                        <?php if ($row2['id'] == $row['modules_id']) echo ' selected'?>
                        ><?php echo $row2['name'] ?></option>
                    <?php } ?>
                </select>
            </td>
            <td class="w-120">
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/delete/' . $row['id'] . $vars['path']) ?>"
                   class="tool-del">Удалить</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
