<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Добавление новой страницы</div>
</div>

<div class="section">
    <form method="POST" name="update-form">
        <div class="section__content section__content-w-50">
            <div class="section__title">Общая информация</div>
            <div class="section__field">
                <label class="required">Название:<span>*</span></label>
                <input type="text" class="form-control" value="" name="name"/>
            </div>
            <div class="section__field">
                <label class="required">Ссылка:<span>*</span>
                    <div class="section__no-link">
                        <input type="checkbox" value="no-link" id="noLink" name="no-link" class="custom-control-label">
                        <label for="noLink">не указывать ссылку</label>
                    </div>
                </label>
                <input type="text" class="form-control" value="" name="link"/>
            </div>
            <div class="section__field">
                <label class="required">Шаблон<span>*</span></label>
                <select class="custom-select" name="template_name">
                    <option value="">не указан</option>
                    <?php foreach ($vars['template'] as $row) { ?>
                        <option value='<?php echo $row ?>'><?php echo $row ?></option>
                    <?php } ?>
                </select>
            </div>

            <div class="section__field">
                <label class="required">Состояние:<span>*</span></label>
                <div class="select-field">
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="1" id="page_data_0_d"
                               name="active" checked="checked">
                        <label for="page_data_0_d">Вкл.</label>
                    </div>
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="0" id="page_data_0_a"
                               name="active">
                        <label for="page_data_0_a">Выкл.</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="section__content section__content-w-50">
            <div class="section__title">SEO - секция</div>
            <div class="section__field">
                <label>Title:</label>
                <input type="text" class="form-control" value="" name="title"/>
            </div>
            <div class="section__field">
                <label>Description:</label>
                <textarea class="form-textarea form-textarea__h-120 no-size"
                          name="description"></textarea>
            </div>
        </div>


        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="add">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="add_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>
