<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Редактирование страницы:&nbsp;<b><?php echo $vars['edit']['name'] ?></b></div>
</div>

<div class="tool">
    <a class="tool__link" href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/add') ?>">Добавить
        раздел</a>
    <a class="tool__link"
       href="/<?php echo PathToTemplateAdmin . '/' . $vars['action'] ?>/delete/<?php echo $vars['edit']['id'] ?>">
        Удалить этот раздел
    </a>
    <a class="tool__link" href="<?php echo Links::getURl($vars['edit']['link']) ?>"
       title="<?php echo $vars['edit']['link'] ?>"
       target="_blank">Предпросмотр</a>
</div>
<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__content section__content-w-50">
            <div class="section__title">Общая информация</div>
            <div class="section__field">
                <label class="required">Название:<span>*</span>
                </label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['name'] ?>"
                       name="name"/>
            </div>

            <div class="section__field">
                <label class="required">
                    Ссылка:<span>*</span>
                    <div class="section__no-link">
                        <input type="checkbox" value="no-link" id="noLink" name="no-link" class="custom-control-label"
                            <?php if ($vars['edit']['no-link'] == 'no-link') echo ' checked="checked"'; ?>>
                        <label for="noLink">не указывать ссылку</label>
                    </div>
                </label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['link'] ?>"
                       name="link"/>
            </div>

            <div class="section__field">
                <label class="required">Шаблон<span>*</span></label>
                <select class="custom-select" name="template_name">
                    <option value="">не указан</option>
                    <?php foreach ($vars['template'] as $row) { ?>
                        <option value='<?php echo $row ?>' <?php echo ($row == $vars['edit']['template_name'])?' selected':''?>><?php echo $row ?></option>
                    <?php } ?>
                </select>
            </div>

            <div class="section__field">
                <label class="required">Состояние:<span>*</span></label>
                <div class="select-field">
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="1" id="page_data_0_d"
                               name="active" <?php if ($vars['edit']['active'] == 1) echo ' checked="checked"'; ?>>
                        <label for="page_data_0_d">Вкл.</label>
                    </div>
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="0" id="page_data_0_a"
                               name="active" <?php if ($vars['edit']['active'] == 0) echo ' checked="checked"'; ?>>
                        <label for="page_data_0_a">Выкл.</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="section__content section__content-w-50">
            <div class="section__title">SEO - секция</div>
            <div class="section__field">
                <label>Title:</label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['title'] ?>"
                       name="title"/>
            </div>
            <div class="section__field">
                <label>Description:</label>
                <textarea class="form-textarea form-textarea__h-120 no-size"
                          name="description"><?php echo $vars['edit']['description'] ?></textarea>
            </div>
        </div>
        <div class="section__content section__content-w-100">
            <div class="section__title">Наполнение страницы</div>
            <div class="section-info">
                <?php foreach ($vars['constructor']['content_page'] as $content_page) {
                    if (!empty($content_page['template_path']))
                        include $_SERVER['DOCUMENT_ROOT'].'/protection/modules/template/'.PathToTemplateAdmin.'/resource/'.$content_page['template_path'].'/config.phtml';
                    else
                        include $_SERVER['DOCUMENT_ROOT'].'/protection/modules/infoblocks/'.PathToTemplateAdmin.'/resource/'.$content_page['info_path'].'/config.phtml';
                } ?>
            </div>
            <div class="create-section-info">
                <button class="create-section-info__btn">Добавить шаблон</button>
            </div>
        </div>

        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="update">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="update_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>

<div class="modal-constructor">
    <div class="modal-constructor__top">
        <div class="modal-constructor__close">
            <svg><use xlink:href="/resource/<?php echo PathToTemplateAdmin?>/images/svg/svg-sprite.svg#delete"></use></svg>
        </div>
    </div>
    <div class="modal-constructor__tabs modal-constructor-tabs">
        <div class="modal-constructor-tabs__item active" data-id="1">Блоки конструктора</div>
        <div class="modal-constructor-tabs__item" data-id="2">Инфо блоки</div>
    </div>
    <div class="modal-constructor__content scroll-custom">
        <div class="modal-constructor__template" data-id="1">
            <?php foreach ($vars['templates'] as $template) { ?>
                <div class="modal-constructor__item">
                    <?php include $_SERVER['DOCUMENT_ROOT'].'/protection/modules/template/'.PathToTemplateAdmin.'/resource/'.$template['path'].'/options.phtml'?>
                </div>
            <?php } ?>
        </div>
        <div class="modal-constructor__template" data-id="2">
            <?php foreach ($vars['info_block_templates'] as $template) { ?>
                <div class="modal-constructor__item">
                    <?php include $_SERVER['DOCUMENT_ROOT'].'/protection/modules/infoblocks/'.PathToTemplateAdmin.'/resource/'.$template['path'].'/options.phtml'?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<div class="modal-constructor-overflow"></div>
