<div class="forgot">
    <div class="forgot__content">
        <div class="forgot__left">
            <div class="forgot__logo">
                <svg>
                    <use xlink:href="/resource/administrator-cms/images/svg/svg-sprite.svg#admin-logo"></use>
                </svg>
                <span>admin panel</span>
            </div>
            <div class="forgot__title">Сброс пароля</div>
            <div class="forgot__desc">Введите свой логин или почту и мы вышлем вам пароль</div>
            <form class="forgot__form" method="POST">
                <div class="form-group forgot__user">
                    <label>Логин или почта:</label>
                    <input type="text" tabindex="1" name="email" class="form-control">
                </div>
                <button type="submit" tabindex="2" class="forgot__btn">Восстановить</button>
            </form>
        </div>
        <div class="forgot__right">
            <img src="/resource/administrator-cms/images/auth-bg.jpg" alt="">
        </div>
    </div>
    <div class="forgot__back">
        Вернуть на страницу <a href="<?php echo Links::getAdminURl('administrator-cms')?>">Авторизации</a>
    </div>
</div>