<?php echo (!empty($vars['error']))?$vars['error']:''?>
<div class="sign-in">
    <div class="sign-in__content">
        <div class="sign-in__left">
            <div class="sign-in__logo">
                <svg>
                    <use xlink:href="/resource/administrator-cms/images/svg/svg-sprite.svg#admin-logo"></use>
                </svg>
                <span>admin panel</span>
            </div>
            <div class="sign-in__title">Добро пожаловать</div>
            <div class="sign-in__desc">Введите свой логин и пароль чтоб зайти в админ панель сайта</div>
            <form class="sign-in__form" method="POST">
                <div class="form-group sign-in__user">
                    <label>Логин:</label>
                    <input type="text" tabindex="1" name="login" class="form-control">
                </div>
                <div class="form-group sign-in__pass">
                    <a class="forgot-link" href="<?php echo Links::getAdminURl('/administrator-cms/forgot')?>">Забыли пароль?</a>
                    <label>Пароль:</label>
                    <input type="password" tabindex="2" name="password" class="form-control">
                </div>
                <div class="form-checkbox mt--10">
                    <input type="checkbox" value="remember" id="remember" name="remember" class="custom-control-label" checked>
                    <label for="remember">Запомнить</label>
                </div>

                <button type="submit" tabindex="3" class="sign-in__btn">Войти</button>
            </form>
        </div>
        <div class="sign-in__right">
            <img src="/resource/administrator-cms/images/auth-bg.jpg" alt="">
        </div>
    </div>
</div>







