<div id="message"><?php echo $vars['message'] ?></div>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title"><?php echo $vars['name'] ?></div>
    <div class="main__tools tools">
        <div class="tools__item action-add">
            <svg>
                <use xlink:href="/resource/<?php echo PathToTemplateAdmin ?>/images/svg/svg-sprite.svg#plus"></use>
            </svg>
            <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/add/tt' . $vars['path']) ?>">Создать</a>
        </div>
    </div>
</div>

<div class="main__content">
    <div class="main__left">
        <div class="main-section">
            <div class="main-section__top main-section-top">
                <input type="text" id="search-form" class="form-control w-300" placeholder="Поиск" value="">
            </div>
            <form name="user-list" method="post"
                  action="/<?php echo PathToTemplateAdmin ?>/<?php echo $vars['action'] . $vars['path'] ?>/update">
                <div class="result-form">
                    <?php echo $vars['list'] ?>
                </div>
                <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
                <div class="button-list">
                    <div class="btn-save">
                        <input type="submit" value="Сохранить" name="update">
                    </div>
                    <div class="btn-del">
                        <input type="submit" value="Удалить выбранные" name="delete">
                    </div>
                </div>
            </form>
        </div>
    </div>

<script>
	document.getElementById("search-form").addEventListener("keyup", function () {
		var message = this.value;
		var xhr = new XMLHttpRequest();
		xhr.open("POST", '/<?php echo PathToTemplateAdmin?>/ajax/config/search');
		xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
		xhr.onreadystatechange = function () {
			if (this.readyState == 4) {
				if (this.status == 200) {
					var json = JSON.parse(this.responseText);
					if (json.status == true) $(".result-form").html(json.content);
				}
			}
		};
		xhr.send("message=" + message);
	});
</script>