    <div class="items-container multi-level">
      <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort table_982px">
        <tr>
          <th width="30">ID</th>
          <th>Комментарий</th>
          <th width="550">Значение</th>
        </tr>

        <? foreach ($vars['list'] as $row) {
          $input = '';
          if ($row['type'] == 'text') $input = '<input type="text" name="value' . $row['id'] . '" value="' . $row['value'] . '" class="input-text" style="width:390px;" />';
          elseif ($row['type'] == 'checkbox') {
            $checked = '';
            if ($row['value'] == 1) $checked = ' checked="checked"';
            $input = '<label class="switch"><input type="checkbox" name="value' . $row['id'] . '" value="1" ' . $checked . ' class="switch-input" /><span class="switch-label" data-on="Да" data-off="Нет"></span><span class="switch-handle"></span></label>';
          } elseif ($row['type'] == 'radio') {
            $checked0 = '';
            $checked1 = '';
            if ($row['value'] == 1) $checked1 = ' checked="checked"';
            else $checked0 = ' checked="checked"';
            $input = '<input type="radio" name="value' . $row['id'] . '" value="0" ' . $checked0 . ' /><input type="radio" name="value' . $row['id'] . '" value="1" ' . $checked1 . ' />';
          } elseif ($row['type'] == 'textarea') {
            $input = '<textarea name="value' . $row['id'] . '" class="input-textarea" style="resize: none; height:26; width:390px;">' . $row['value'] . '</textarea>';
          } ?>

          <tr>
            <td><span><?= $row['id'] ?></span><input type="hidden" value="<?= $row['id'] ?>" name="save_id[]"/></td>
            <td><textarea name="comment[]" class="input-textarea" style="resize: none; height:26px; width:350px;"><?= $row['comment'] ?></textarea>
            </td>
            <td><?= $input ?></td>
          </tr>
        <? } ?>
      </table>
    </div>