<ul class="social-block">
    <?php if (!empty($vars['social']['youtube'])) { ?>
        <li>
            <a rel="nofollow" href="<?php echo $vars['social']['youtube'] ?>" target="_blank">
                <svg class="icon-social icon-youtube">
                    <use xlink:href="/resource/front/img/svg/svg-sprite.svg#youtube"></use>
                </svg>
            </a>
        </li>
    <?php } ?>
    <?php if (!empty($vars['social']['instagram'])) { ?>
        <li>

            <a rel="nofollow" href="<?php echo $vars['social']['instagram'] ?>" target="_blank">
                <svg class="icon-social icon-instagram">
                    <use xlink:href="/resource/front/img/svg/svg-sprite.svg#instagram"></use>
                </svg>
            </a>
        </li>
    <?php } ?>
    <?php if (!empty($vars['social']['facebook'])) { ?>
        <li>
            <a rel="nofollow" href="<?php echo $vars['social']['facebook'] ?>" target="_blank">
                <svg class="icon-social icon-facebook">
                    <use xlink:href="/resource/front/img/svg/svg-sprite.svg#facebook"></use>
                </svg>
            </a>
        </li>
    <?php } ?>
    <?php if (!empty($vars['social']['pinterest'])) { ?>
        <li>
            <a rel="nofollow" href="<?php echo $vars['social']['pinterest'] ?>" target="_blank">
                <svg class="icon-social icon-pinterest">
                    <use xlink:href="/resource/front/img/svg/svg-sprite.svg#pinterest"></use>
                </svg>
            </a>
        </li>
    <?php } ?>
    <?php if (!empty($vars['social']['telegram'])) { ?>
        <li>
            <a rel="nofollow" href="<?php echo $vars['social']['telegram'] ?>" target="_blank">
                <svg class="icon-social icon-telegram">
                    <use xlink:href="/resource/front/img/svg/svg-sprite.svg#telegram"></use>
                </svg>
            </a>
        </li>
    <?php } ?>
    <?php if (!empty($vars['social']['viber'])) { ?>
        <li>
            <a rel="nofollow" href="<?php echo $vars['social']['viber'] ?>" target="_blank">
                <svg class="icon-social icon-viber">
                    <use xlink:href="/resource/front/img/svg/svg-sprite.svg#viber"></use>
                </svg>
            </a>
        </li>
    <?php } ?>
</ul>

