<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Редактирование блока:&nbsp;<b><?php echo $vars['edit']['name'] ?></b></div>
</div>

<div class="tool">
    <a class="tool__link" href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/add') ?>">Добавить
        раздел</a>
    <a class="tool__link"
       href="/<?php echo PathToTemplateAdmin . '/' . $vars['action'] ?>/delete/<?php echo $vars['edit']['id'] ?>">
        Удалить этот раздел
    </a>
    <a class="tool__link" href="<?php echo Links::getURl($vars['edit']['link']) ?>"
       title="<?php echo $vars['edit']['link'] ?>"
       target="_blank">Предпросмотр</a>
</div>
<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__content section__content-w-100">
            <div class="section__title">Общая информация</div>
            <div class="section__field">
                <label class="required">Название блока:<span>*</span>
                </label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['name'] ?>"
                       name="name"/>
            </div>
            <div class="section__field">
                <label class="required">Тип блока:<span>*</span></label>
                <select class="custom-select infoblock-select" name="type">
                    <?php foreach ($vars['type'] as $row) { ?>
                        <option value='<?php echo $row['id'] ?>' <?php echo ($row['id'] == $vars['edit']['type']) ? 'selected' : '' ?>>
                            <?php echo $row['name'] ?>
                        </option>
                    <?php } ?>
                </select>
            </div>
            <div class="section__field">
                <label>Шаблон: <b><?php echo $vars['edit']['path'] ?></b></label>
            </div>
            <div class="section__template">
                <?php include $_SERVER['DOCUMENT_ROOT'] . '/protection/modules/infoblocks/' . PathToTemplateAdmin . '/resource/' . $vars['edit']['path'] . '/config_content.phtml' ?>
            </div>
        </div>

        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="update">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="update_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>



