<div class="main__title" style="margin-bottom: 20px"><?php echo $vars['name'] ?></div>
<table class="table">
    <thead>
    <tr>
        <th width="50">ID</th>
        <th>Название</th>
        <th width="160">Действие</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($vars['list_info'] as $row) { ?>
        <tr>
            <td><?php echo $row['id'] ?></td>
            <td><?php echo $row['name'] ?></td>
            <td class="d-flex justify-content-between align-items-center h-65">
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/edit/' . $row['id']) ?>"
                   class="tool-edit">Редакт.</a>
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/delete/' . $row['id']) ?>"
                   class="tool-del">Удалить</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<div class="main__title" style="margin-top: 50px;margin-bottom: 20px"><?php echo $vars['name'] ?> - конструктор</div>
<table class="table">
    <thead>
    <tr>
        <th width="50">ID</th>
        <th>Название</th>
        <th width="160">Действие</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($vars['list_info_template'] as $row) { ?>
        <tr>
            <td><?php echo $row['id'] ?></td>
            <td><?php echo $row['name'] ?></td>
            <td class="d-flex justify-content-between align-items-center h-65">
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/edit/' . $row['id']) ?>"
                   class="tool-edit">Редакт.</a>
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/delete/' . $row['id']) ?>"
                   class="tool-del">Удалить</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
