<?php echo $vars['message'] ?>
<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Добавление нового языка</div>
</div>
<div class="section">
    <form method="POST" name="update-form">
        <div class="section__content section__content-w-50">
            <div class="section__field">
                <label class="required">Название:<span>*</span></label>
                <input type="text" class="form-control" value="" name="comment"/>
            </div>
            <div class="section__field">
                <label class="required">Сокращение:<span>*</span></label>
                <input type="text" class="form-control" value="" name="comment_low"/>
            </div>
            <div class="section__field">
                <label class="required">Префикс:</label>
                <select class="custom-select" name="language">
                    <option value="0">Корневой раздел</option>
                    <?php foreach ($vars['Language'] as $lang) { ?>
                        <option value='<?php echo $lang ?>'><?php echo $lang ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="add">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="add_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>