<div class="paging">
    <ul class="paging__list">
        <?php
        $page_size = $vars['page_size'];
        $link_padding = $vars['link_padding'];
        $cur_page = $vars['page'];
        $page_var = $vars['page_var'];
        $total_pages = $vars['count'];

        $page_link_list = array();
        $start = $cur_page - $link_padding;
        if ($start < 1) $start = 1;
        $end = $cur_page + $link_padding - 1;
        if ($end > $total_pages)
            $end = $total_pages;
        if ($cur_page > 1)
            $prev_page = $cur_page - 1;
        else
            $prev_page = 1;
        if ($cur_page < $total_pages)
            $next_page = $cur_page + 1;
        else
            $next_page = $total_pages;
        if ($start > 1) {
            $page_link_list[] = StringClass::get_page_link(1, $cur_page, $page_var);
        }
        if ($start > 1) {
            $page_link_list[] = StringClass::get_page_link($start - 1, $cur_page, $page_var, $start - 2 > 0 ? '...' : '');
        }

        if ($cur_page != $prev_page) {
            if ($prev_page == 1)
                echo '<li class="paging__prev "><a href="' . str_replace('//', '', StringClass::getUrl2('page')) . '" class="paging__link"><svg><use xlink:href="/resource/front/img/svg/svg-sprite.svg#arrow-left"></use></svg></a></li>';
            else
                echo '<li class="paging__prev"><a href="' . str_replace('//', '/', StringClass::getUrl2('page') . '/page/' . $prev_page) . '" class="paging__link"><svg><use xlink:href="/resource/front/img/svg/svg-sprite.svg#arrow-left"></use></svg></a></li>';
        }
        for ($i = $start; $i <= $end; $i++) {
            if ((abs($i - $cur_page) > 1) && ($i > 2) && ($i < $total_pages - 2))
                continue;
            $page_link_list[] = StringClass::get_page_link($i, $cur_page, $page_var);
        }
        if ($end + 1 < $total_pages) {
            $page_link_list[] = StringClass::get_page_link($end + 1, $cur_page, $page_var, $end + 2 == $total_pages ? '' : '...');
        }
        if ($end + 1 <= $total_pages) {
            $page_link_list[] = StringClass::get_page_link($total_pages, $cur_page, $page_var);
        }
        echo implode('', $page_link_list);

        if ($cur_page != $next_page)
            echo '<li class="paging__next"><a href="' . str_replace('//', '/', StringClass::getUrl2('page') . '/page/' . $next_page) . '" class="paging__link"><svg><use xlink:href="/resource/front/img/svg/svg-sprite.svg#arrow-right"></use></svg></a></li>';
        else
        ?>
    </ul>
</div>