<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Редактирование шаблона:&nbsp;<b><?php echo $vars['edit']['name'] ?></b></div>
</div>

<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__content section__content-w-100">
            <div class="section__title">Общая информация</div>
            <div class="section__field">
                <div class="section__field-photo">
                    <?php
                    $photo = $photo = "protection/modules/". $vars['action']."/". PathToTemplateAdmin."/resource/".$vars['edit']['path']."/static/img/preview.jpg";
                    ?>
                    <img src="<?php echo file_exists($photo)?'/'.$photo:'/resource/'. PathToTemplateAdmin.'/images/default.jpg'?>">
                </div>
            </div>

            <div class="section__field">
                <label>Название:</label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['name'] ?>"
                       name="name"/>
            </div>
            <div class="section__field">
                <label>Путь:</label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['path'] ?>"
                       name="path"/>
            </div>

            <div class="section__info-open">
                <span>Данная информация скрыта от обычного использования, и если вы не разработчик, то лучше ничего не изменять</span>
                <button class="open-overflow-content btn-add-in">Открыть/закрыть для редактирования</button>
            </div>
            <div class="section__overflow">
                <div class="section__field">
                    <label>Таблица:</label>
                    <input type="text" class="form-control" value="<?php echo $vars['edit']['module_table'] ?>"
                           name="module_table"/>
                </div>
                <div class="section__field">
                    <label>Нужный тим в модуле:</label>
                    <input type="text" class="form-control" value="<?php echo $vars['edit']['module_table_type'] ?>"
                           name="module_table_type"/>
                </div>
                <div class="section__field">
                    <label>Что выбрать (select):</label>
                    <input type="text" class="form-control" value="<?php echo $vars['edit']['module_select'] ?>"
                           name="module_select"/>
                </div>
                <div class="section__field">
                    <label>Сортировка (sort):</label>
                    <input type="text" class="form-control" value="<?php echo $vars['edit']['module_sort'] ?>"
                           name="module_sort"/>
                </div>
                <div class="section__field">
                    <label>Количество элементов (limit):</label>
                    <input type="text" class="form-control" value="<?php echo $vars['edit']['module_limit'] ?>"
                           name="module_limit"/>
                </div>
            </div>
        </div>
        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="update">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="update_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>



