<div class="section-info__item section-info-item">
    <div class="section-info-item__info">
        <div class="section-info-item__name">
            Название блока: <span>Info</span>
        </div>
        <div class="section-info-item__type">
            Тип блока: <span>конструктор</span>
        </div>
        <div class="section-info-item__sort">
            Позиция блока:
            <input type="text" class="section-info-item__sort-input" value="<?php echo $content_page['sort'] ?>"
                   name="constructor[<?php echo $content_page['id'] ?>][sort]">
        </div>
        <div class="section-info-item__btn">
            <div class="section-info-item__del">
                <button class="btn-del-in del-block-constructor"
                        data-page="<?php echo $vars['edit']['id'] ?>"
                        data-id="<?php echo $content_page['id'] ?>">Удалить
                </button>
            </div>
            <div class="section-info-item__add">
                <button class="btn-add-in add-block-constructor"
                        data-page="<?php echo $vars['edit']['id'] ?>"
                        data-id="<?php echo $content_page['id'] ?>"
                        data-table="constructor_resource">Добавить поле
                </button>
            </div>
        </div>
        <div class="section-info-item__detail show-detail">
            <svg>
                <use xlink:href="/resource/administrator-cms/images/svg/svg-sprite.svg#arrow-down"></use>
            </svg>
        </div>
    </div>
    <div class="section-info-item__preview">
        <img src="/protection/modules/template/administrator-cms/resource/<?php echo $content_page['template_path'] ?>/static/img/preview.jpg">
    </div>
    <div class="section-info-item__content">
        <div class="section-info-item__content-w100">
            <div class="section__field">
                <label>Картинка:</label>
                <?php
                $vars['photo_key'] = 'photo';
                $vars['increment'] = $vars['constructor']['content_page_res'][$content_page['id']][$vars['photo_key']]['id'];
                $vars['image_id'] = $content_page['id'];
                $vars['path'] = "storage/page/" . substr($vars['edit']['id'],
                        -1) . "/" . $vars['edit']['id'] . "/constructor/". $content_page['id'] ."/" . $this->registry['key_lang_admin'] . "/";
                $vars['action_table'] = 'constructor_resource';
                include $_SERVER['DOCUMENT_ROOT'] . "/resource/" . PathToTemplateAdmin . "/photos/constructor/upload_img_lang.phtml";
                ?>
            </div>
            <div class="section__field">
                <label>Заголовок:</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['title']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][title]"/>
            </div>
            <div class="section__field hr-bottom">
                <label>Описание:</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['desc']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][desc]"/>
            </div>

            <div class="section__field">
                <label>Заголовок (о нас):</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_title']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][about_title]"/>
            </div>
            <div class="section__field">
                <label>Картинка (о нас 1):</label>
                <?php
                $vars['photo_key'] = 'about_photo_one';
                $vars['increment'] = $vars['constructor']['content_page_res'][$content_page['id']][$vars['photo_key']]['id'];
                $vars['image_id'] = $content_page['id'];
                $vars['path'] = "storage/page/" . substr($vars['edit']['id'],
                        -1) . "/" . $vars['edit']['id'] . "/constructor/". $content_page['id'] ."/" . $this->registry['key_lang_admin'] . "/";
                $vars['action_table'] = 'constructor_resource';
                include $_SERVER['DOCUMENT_ROOT'] . "/resource/" . PathToTemplateAdmin . "/photos/constructor/upload_img_lang.phtml";
                ?>
            </div>
            <div class="section__field">
                <label>Должность (о нас 1):</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_position_one']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][about_position_one]"/>
            </div>
            <div class="section__field">
                <label>Имя (о нас 1):</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_name_one']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][about_name_one]"/>
            </div>
            <div class="section__field">
                <label>Описание (о нас 1):</label>
                <textarea class="form-textarea form-textarea__h-120 no-size"
                          name="constructor[<?php echo $content_page['id'] ?>][about_desc_one]"><?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_desc_one']['value'] ?></textarea>
            </div>

            <div class="section__field">
                <label>Картинка (о нас 2):</label>
                <?php
                $vars['photo_key'] = 'about_photo_two';
                $vars['increment'] = $vars['constructor']['content_page_res'][$content_page['id']][$vars['photo_key']]['id'];
                $vars['image_id'] = $content_page['id'];
                $vars['path'] = "storage/page/" . substr($vars['edit']['id'],
                        -1) . "/" . $vars['edit']['id'] . "/constructor/". $content_page['id'] ."/" . $this->registry['key_lang_admin'] . "/";
                $vars['action_table'] = 'constructor_resource';
                include $_SERVER['DOCUMENT_ROOT'] . "/resource/" . PathToTemplateAdmin . "/photos/constructor/upload_img_lang.phtml";
                ?>
            </div>
            <div class="section__field">
                <label>Должность (о нас 2):</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_position_two']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][about_position_two]"/>
            </div>
            <div class="section__field">
                <label>Имя (о нас 2):</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_name_two']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][about_name_two]"/>
            </div>
            <div class="section__field">
                <label>Описание (о нас 2):</label>
                <textarea class="form-textarea form-textarea__h-120 no-size"
                          name="constructor[<?php echo $content_page['id'] ?>][about_desc_two]"><?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_desc_two']['value'] ?></textarea>
            </div>

            <div class="section__field">
                <label>Картинка (о нас 2):</label>
                <?php
                $vars['photo_key'] = 'about_photo_three';
                $vars['increment'] = $vars['constructor']['content_page_res'][$content_page['id']][$vars['photo_key']]['id'];
                $vars['image_id'] = $content_page['id'];
                $vars['path'] = "storage/page/" . substr($vars['edit']['id'],
                        -1) . "/" . $vars['edit']['id'] . "/constructor/". $content_page['id'] ."/" . $this->registry['key_lang_admin'] . "/";
                $vars['action_table'] = 'constructor_resource';
                include $_SERVER['DOCUMENT_ROOT'] . "/resource/" . PathToTemplateAdmin . "/photos/constructor/upload_img_lang.phtml";
                ?>
            </div>
            <div class="section__field">
                <label>Должность (о нас 2):</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_position_three']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][about_position_three]"/>
            </div>
            <div class="section__field">
                <label>Имя (о нас 2):</label>
                <input type="text" class="form-control"
                       value="<?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_name_three']['value'] ?>"
                       name="constructor[<?php echo $content_page['id'] ?>][about_name_three]"/>
            </div>
            <div class="section__field">
                <label>Описание (о нас 2):</label>
                <textarea class="form-textarea form-textarea__h-120 no-size"
                          name="constructor[<?php echo $content_page['id'] ?>][about_desc_three]"><?php echo $vars['constructor']['content_page_res'][$content_page['id']]['about_desc_three']['value'] ?></textarea>
            </div>
        </div>

        <div class="section-info-item__content-w100">
            <?php foreach ($vars['constructor']['content_page_res'][$content_page['id']] as $key => $item) {
                if (!empty($item['name_admin'])) { ?>
                    <div class="section__field">
                        <label><?php echo $item['name_admin'] ?>:</label>
                        <input type="text" class="form-control"
                               value="<?php echo $item['value'] ?>"
                               name="constructor[<?php echo $content_page['id'] ?>][<?php echo $key ?>]"/>
                    </div>
                <?php }
            } ?>
        </div>
    </div>
</div>

