<div class="faq-meta__left">
    <input type="hidden" value="<?php echo $vars['meta_id'] ?>" name="meta_id[]">
    <div class="section__field">
        <label>Вопрос:</label>
        <input type="text" class="form-control" id="page_page_title" name="quest[]"/>
    </div>
    <div class="section__field">
        <label>Ответ:</label>
        <textarea class="form-textarea form-textarea__h-120 no-size" id="page_meta_descr" name="ans[]"></textarea>
    </div>
</div>