<script type="text/javascript">
    $(function () {
        $("#tree").treeview({
            collapsed: true,
            animated: "medium",
            control: "#sidetreecontrol",
            persist: "location"
        });
    })
</script>
<div class="list-group">
    <div class="list-group__title">
        <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/menu')?>">
            <svg><use xlink:href="/resource/administrator-cms/images/svg/svg-sprite.svg#home"></use></svg>
            <span>Корневой раздел</span>
        </a>
    </div>
    <div class="list-group__list">
        <?php echo $vars['cat_menu'] ?>
    </div>
</div>
