<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Редактирование раздела:&nbsp;<b><?php echo $vars['edit']['name'] ?></b></div>
</div>

<div class="tool">
    <a class="tool__link" href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/add') ?>">Добавить товар</a>
    <a class="tool__link" href="/<?php echo PathToTemplateAdmin . '/' . $vars['action'] ?>/delete/<?php echo $vars['edit']['id'] ?>">
        Удалить этот товар
    </a>
    <a class="tool__link" href="<?php echo Links::getURl($vars['edit']['link']) ?>"
       title="<?php echo $vars['edit']['link'] ?>"
       target="_blank">Предпросмотр</a>
</div>

<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__content section__content-w-50">
            <div class="section__title">Общая информация</div>
            <div class="section__field">
                <label class="required">Родительская раздел:<span>*</span></label>
                <select class="custom-select" name="sub">
                    <option value="0">Корневой раздел</option>
                    <?php foreach ($vars['catalog'] as $row) { ?>
                        <option value='<?php echo $row['id'] ?>' <?php echo ($row['id'] == $vars['edit']['sub'])?' selected':''?>><?php echo $row['name'] ?></option>
                        <?php if (!empty($row['childs'])) { ?>
                            <?php foreach ($row['childs'] as $child) { ?>
                                <option value='<?php echo $child['id'] ?>' <?php echo ($child['id'] == $vars['edit']['sub'])?' selected':''?>>
                                    &nbsp;&nbsp;&nbsp<?php echo $child['name'] ?></option>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                </select>
            </div>
            <div class="section__field">
                <label class="required">Позиция меню:<span>*</span></label>
                <select class="custom-select infoblock-select" name="type">
                    <?php foreach ($vars['type'] as $row) { ?>
                        <option value='<?php echo $row['id'] ?>' <?php echo ($row['id'] == $vars['edit']['type_id']) ? 'selected' : '' ?>>
                            <?php echo $row['name'] ?>
                        </option>
                    <?php } ?>
                </select>
            </div>
            <div class="section__field">
                <label class="required">Название:<span>*</span>
                </label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['name'] ?>"
                       name="name"/>
            </div>
            <div class="section__field">
                <label class="required">Ссылка:<span>*</span>
                </label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['link'] ?>"
                       name="link"/>
            </div>

            <div class="section__field">
                <label class="required">Ссылка на внешний рессурс:</label>
                <div class="select-field">
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="1" id="page_blank_0_d"
                               name="blank" <?php if ($vars['edit']['blank'] == 1) echo ' checked="checked"'; ?>>
                        <label for="page_blank_0_d">Да</label>
                    </div>
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="0" id="page_blank_0_a"
                               name="blank" <?php if ($vars['edit']['blank'] == 0) echo ' checked="checked"'; ?>>
                        <label for="page_blank_0_a">Нет</label>
                    </div>
                </div>
            </div>

            <div class="section__field">
                <label class="required">Состояние:<span>*</span></label>
                <div class="select-field">
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="1" id="page_data_0_d"
                               name="active" <?php if ($vars['edit']['active'] == 1) echo ' checked="checked"'; ?>>
                        <label for="page_data_0_d">Вкл.</label>
                    </div>
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="0" id="page_data_0_a"
                               name="active" <?php if ($vars['edit']['active'] == 0) echo ' checked="checked"'; ?>>
                        <label for="page_data_0_a">Выкл.</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="section__content section__content-w-50">
            <div class="section__title">SEO - секция</div>
            <div class="section__field">
                <label>Title:</label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['title'] ?>"
                       name="title"/>
            </div>
            <div class="section__field">
                <label>Description:</label>
                <textarea class="form-textarea form-textarea__h-120 no-size"
                          name="description"><?php echo $vars['edit']['description'] ?></textarea>
            </div>
        </div>
        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="update">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="update_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>



