<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title"><?php echo $vars['name'] ?></div>
    <div class="main__tools tools">
        <div class="tools__item action-add">
            <svg>
                <use xlink:href="/resource/<?php echo PathToTemplateAdmin ?>/images/svg/svg-sprite.svg#plus"></use>
            </svg>
            <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/add') ?>">Создать</a>
        </div>
    </div>
</div>

<div class="main__content">
    <div class="main__left">
        <div class="main-section">
            <div class="position">
                <form method="post" class="position__item <?php echo (0 == $_SESSION['info_sort_position_id']) ? 'active' : '' ?>">
                    <div class="position__name">Все слайды</div>
                    <div class="position__btn">
                        <input type="hidden" name="getPosition" value="0">
                        <input type="submit" name="getPositionUpdate" value="Перейти"
                               onchange="this.form.submit()">
                    </div>
                </form>
                <?php foreach ($vars['type'] as $type) { ?>
                    <form method="post"
                          class="position__item <?php echo ($type['id'] == $_SESSION['info_sort_position_id']) ? 'active' : '' ?>">
                        <div class="position__name"><?php echo $type['name'] ?></div>
                        <div class="position__btn">
                            <input type="hidden" name="getPosition" value="<?php echo $type['id'] ?>">
                            <input type="submit" name="getPositionUpdate" value="Перейти"
                                   onchange="this.form.submit()">
                        </div>
                    </form>
                <?php } ?>
            </div>
            <form name="user-list" method="post" action="/<?php echo PathToTemplateAdmin ?>/<?php echo $vars['action'] ?>/update">
                <?php echo $vars['list'] ?>
                <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
                <div class="button-list">
                    <div class="btn-save">
                        <input type="submit" value="Сохранить" name="update">
                    </div>
                    <div class="btn-del">
                        <input type="submit" value="Удалить выбранные" name="delete">
                    </div>
                </div>
            </form>
        </div>
    </div>


