<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Редактирование модуля:&nbsp;<b><?php echo $vars['edit']['name'] ?></b></div>
</div>

<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__content section__content-w-50">
            <div class="section__title">Общая информация</div>
            <div class="section__field">
                <label class="required">Название:<span>*</span></label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['name'] ?>" name="name"/>
            </div>
            <div class="section__field">
                <label>Ссылка:</label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['link'] ?>" name="link"/>
            </div>
            <div class="section__field">
                <label>Таблицы:</label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['tables'] ?>" name="tables"/>
            </div>
            <div class="section__field">
                <label class="required">Раздел:<span>*</span></label>
                <select class="custom-select" name="sub">
                    <option value="0">Выберите раздел</option>
                    <?php foreach ($vars['menu'] as $row) { ?>
                        <option value="<?php echo $row['id'] ?>" <?php echo ($row['id'] == $vars['edit']['sub'])?'selected':''?>>
                            <?php echo $row['name'] ?>
                        </option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="update">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="update_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>
