<div class="section-info-item-prev">
    <div class="section-info-item-prev__info">
        <div class="section-info-item-prev__name">
            Название: <span><?php echo $template['name']?></span>
        </div>
        <div class="section-info-item-prev__add">
            <button class="btn-save-in save-block-constructor">Добавить</button>
        </div>
    </div>
    <div class="section-info-item-prev__preview">
        <img src="/protection/modules/template/<?php echo PathToTemplateAdmin ?>/resource/<?php echo $template['path'] ?>/static/img/preview.jpg">
    </div>
    <input type="hidden" name="info[page_id]" value="<?php echo $vars['edit']['id']?>"/>
    <input type="hidden" name="info[template_id]" value="<?php echo $template['id']?>"/>

    <input type="hidden" name="constructor[title]"/>
    <input type="hidden" name="constructor[desc]"/>
    <input type="hidden" name="constructor[link_btn]"/>
    <input type="hidden" name="constructor[name_btn]"/>

    <input type="hidden" name="constructor[title_two]"/>
    <input type="hidden" name="constructor[desc_two]"/>
</div>

