<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Редактирование раздела:&nbsp;<b><?php echo $vars['edit']['name'] ?></b></div>
</div>

<div class="tool">
    <a class="tool__link" href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/add') ?>">Добавить товар</a>
    <a class="tool__link" href="/<?php echo PathToTemplateAdmin . '/' . $vars['action'] ?>/delete/<?php echo $vars['edit']['id'] ?>">
        Удалить этот товар
    </a>
    <a class="tool__link" href="<?php echo Links::getURl($vars['edit']['link']) ?>"
       title="<?php echo $vars['edit']['link'] ?>"
       target="_blank">Предпросмотр</a>
</div>

<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__content section__content-w-100">
            <div class="section__title">Общая информация</div>
            <div class="section__field">
                <label>Название:</label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['name'] ?>"
                       name="name"/>
            </div>
            <div class="section__field">
                <label>Ссылка:</label>
                <input type="text" class="form-control" value="<?php echo $vars['edit']['link'] ?>"
                       name="link"/>
            </div>
            <div class="section__field">
                <label>Иконка:</label>
                <textarea class="form-textarea form-textarea__h-120 no-size"
                          name="icon"><?php echo $vars['edit']['icon'] ?></textarea>
            </div>
        </div>
        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="update">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="update_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>



