<table class="table tb_sort">
    <thead>
    <tr>
        <th width="50">ID</th>
        <th>Ссылка</th>
        <th width="160">Действие</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($vars['list'] as $row) { ?>
        <tr id="sort<?php echo $row['id'] ?>" style="background-color: <?php echo $row['type_color']?>">
            <td><?php echo $row['id'] ?></td>
            <td><?php echo $row['link'] ?></td>
            <td class="d-flex justify-content-between align-items-center h-65">
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/edit/' . $row['id']) ?>"
                   class="tool-edit">Редакт.</a>
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/delete/' . $row['id']) ?>"
                   class="tool-del">Удалить</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
