<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title"><?php echo $vars['name'] ?></div>
</div>


<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__content section__content-w-100">
            <table class="table">
                <thead>
                <tr>
                    <th width="50">Состояние</th>
                    <th>Модуль</th>
                    <th>Имя файла</th>
                    <th>Ссылка</th>
                    <th>Приоритет</th>
                    <th>Удалить страницы</th>
                </tr>
                </thead>
                <tbody class="sitemap-section__content">
                    <?php foreach ($vars['list'] as $row) { ?>
                    <tr>
                        <td>
                            <div class="select-field">
                                <div class="select-field__item">
                                    <input type="radio" class="select-field__radio" value="1" id="page_data_0_d"
                                           name="active" <?php if ($row['active'] == 1) echo ' checked="checked"'; ?>>
                                    <label for="page_data_0_d">Вкл.</label>
                                </div>
                                <div class="select-field__item">
                                    <input type="radio" class="select-field__radio" value="0" id="page_data_0_a"
                                           name="active" <?php if ($row['active'] == 0) echo ' checked="checked"'; ?>>
                                    <label for="page_data_0_a">Выкл.</label>
                                </div>
                            </div>
                        </td>
                        <td><input type="text" value="<?php echo $row['module']?>" name="module[]" class="form-control"></td>
                        <td><input type="text" value="<?php echo $row['name_file']?>" name="name_file[]" class="form-control"></td>
                        <td>
                            <span><?php echo PROTOCOL . $_SERVER['HTTP_HOST']?></span>
                            <input type="text" value="<?php echo $row['name_link']?>" name="name_link[]" class="form-control">
                        </td>
                        <td>
                            <input type="hidden" value="<?php echo $row['id'] ?>" name="save_id[]"/>
                            <select class="custom-select" name="priority[]">
                                <?php foreach ($vars['priority'] as $priority) { ?>
                                    <option value='<?php echo $priority ?>' <?php echo ($priority == $row['priority']) ? ' selected' : '' ?>><?php echo $priority ?></option>
                                <?php } ?>
                            </select>
                        </td>
                        <td>
                            <textarea class="form-textarea no-size" name="exclude[]"><?php echo $row['exclude']?></textarea>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <div class="sitemap-section__bnt">
                <div class="action-add add-sitemap">
                    <svg>
                        <use xlink:href="/resource/administrator-cms/images/svg/svg-sprite.svg#plus"></use>
                    </svg>
                    <a>Добавить модуль</a>
                </div>
            </div>
        </div>


        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="save">
            </div>
            <div class="btn-save" style="background-color: #d30000">
                <input type="submit" value="Обновить" name="update">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>
