
<?php if (isset($vars['menu']) && count($vars['menu']) != 0) { ?>
    <div class="list-group">
        <div class="list-group__title">
            <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin. '/' . $vars['action']) ?>">
                <svg><use xlink:href="/resource/administrator-cms/images/svg/svg-sprite.svg#home"></use></svg>
                <span>Корневой раздел</span>
            </a>
        </div>
        <ul class="list-group__list">
            <?php foreach ($vars['menu'] as $row) { ?>
                <li class="<?php echo ($_SERVER['REQUEST_URI'] == Links::getAdminURl($row['link'])) ? 'active' : '' ?>">
                    <svg><use xlink:href="/resource/<?php echo PathToTemplateAdmin?>/images/svg/svg-sprite.svg#<?php echo $row['icon']?>"></use></svg>
                    <a href="<?php echo Links::getAdminURl($row['link']) ?>"><?php echo $row['title'] ?></a>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>