<?php
$input = '';
if ($row['type'] == 'text') $input = '<input type="text" name="value' . $row['id'] . '" value="' . $row['value'] . '" class="form-control" />';
elseif ($row['type'] == 'checkbox') {
    $checked = '';
    if ($row['value'] == 1) $checked = ' checked="checked"';
    $input = '<label class="switch"><input type="checkbox" name="value' . $row['id'] . '" value="1" ' . $checked . ' class="switch-input" /><span class="switch-label" data-on="Да" data-off="Нет"></span><span class="switch-handle"></span></label>';
} elseif ($row['type'] == 'radio') {
    $checked0 = '';
    $checked1 = '';
    if ($row['value'] == 1) $checked1 = ' checked="checked"';
    else $checked0 = ' checked="checked"';
    $input = '<input type="radio" name="value' . $row['id'] . '" value="0" ' . $checked0 . ' /><input type="radio" name="value' . $row['id'] . '" value="1" ' . $checked1 . ' />';
} elseif ($row['type'] == 'textarea') $input = '<textarea name="value' . $row['id'] . '" class="input-textarea" style="resize: none; height:17px; width:190px;">' . $row['value'] . '</textarea>';
