<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Новые мета данные</div>
</div>

<div class="section">
    <form method="POST" name="update-form">
        <div class="section__content section__content-w-50">
            <div class="section__title">Общая информация</div>
            <p>URL адреса для мета данных относительные. Пример: <i>/about</i></p>
            <p>Для отображение текста на странице - заполните мета-данные (title, description)</p>
            <div class="section__field">
                <label class="required">Ссылка:<span>*</span></label>
                <input type="text" class="form-control" value="" name="link"/>
            </div>
            <div class="section__field">
                <label>Тип: </label>
                <div class="select-field">
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="0" id="page_d0"
                               name="type" checked="checked">
                        <label for="page_d0">Выкл.</label>
                    </div>
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="1" id="page_d1"
                               name="type">
                        <label for="page_d1">Мета данные каталога</label>
                    </div>
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="2" id="page_d2"
                               name="type">
                        <label for="page_d2">Мета данные товара</label>
                    </div>
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="3" id="page_d3"
                               name="type">
                        <label for="page_d3">Мета данные для отзывов товара</label>
                    </div>
                </div>
            </div>
            <div class="section__field">
                <label class="required">Состояние:<span>*</span></label>
                <div class="select-field">
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="1" id="page_data_0_d"
                               name="active" checked="checked">
                        <label for="page_data_0_d">Вкл.</label>
                    </div>
                    <div class="select-field__item">
                        <input type="radio" class="select-field__radio" value="0" id="page_data_0_a"
                               name="active">
                        <label for="page_data_0_a">Выкл.</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="section__content section__content-w-50">
            <div class="section__title">SEO - секция</div>
            <div class="section__field">
                <label>Title:</label>
                <input type="text" class="form-control" value="" name="title"/>
            </div>
            <div class="section__field">
                <label>Description:</label>
                <textarea class="form-textarea form-textarea__h-120 no-size"
                          name="description"></textarea>
            </div>
        </div>
        <div class="section__content section__content-w-100">
            <div class="section__editor">
                <label>Описание:</label>
                <?php echo showEditor('body', '')?>
            </div>
        </div>

        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="add">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="add_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>