<?php echo $vars['message'] ?>

<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Редактирование мета данных:&nbsp;<b><?php echo $vars['edit']['name'] ?></b></div>
</div>

<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__nav nav">
            <div class="nav__list">
                <div class="nav__item active" data-open="default">Общее</div>
                <div class="nav__item" data-open="faq">FAQ</div>
            </div>
        </div>
        <div class="tabs tabs-section-default">
            <div class="section__content section__content-w-50">
                <div class="section__title">Общая информация</div>
                <p>URL адреса для мета данных относительные. Пример: <i>/about</i></p>
                <p>Для отображение текста на странице - заполните мета-данные (title, description)</p>
                <div class="section__field">
                    <label class="required">Ссылка:<span>*</span>
                    </label>
                    <input type="text" class="form-control" value="<?php echo $vars['edit']['link'] ?>"
                           name="link"/>
                </div>
                <div class="section__field">
                    <label>Тип: </label>
                    <div class="select-field">
                        <div class="select-field__item">
                            <input type="radio" class="select-field__radio" value="0" id="page_d0"
                                   name="type" <?php if ($vars['edit']['type'] == 0) echo ' checked="checked"'; ?>>
                            <label for="page_d0">Выкл.</label>
                        </div>
                        <div class="select-field__item">
                            <input type="radio" class="select-field__radio" value="1" id="page_d1"
                                   name="type" <?php if ($vars['edit']['type'] == 1) echo ' checked="checked"'; ?>>
                            <label for="page_d1">Мета данные каталога</label>
                        </div>
                        <div class="select-field__item">
                            <input type="radio" class="select-field__radio" value="2" id="page_d2"
                                   name="type" <?php if ($vars['edit']['type'] == 2) echo ' checked="checked"'; ?>>
                            <label for="page_d2">Мета данные товара</label>
                        </div>
                        <div class="select-field__item">
                            <input type="radio" class="select-field__radio" value="3" id="page_d3"
                                   name="type" <?php if ($vars['edit']['type'] == 3) echo ' checked="checked"'; ?>>
                            <label for="page_d3">Мета данные для отзывов товара</label>
                        </div>
                    </div>
                </div>
                <div class="section__field">
                    <label class="required">Состояние:<span>*</span></label>
                    <div class="select-field">
                        <div class="select-field__item">
                            <input type="radio" class="select-field__radio" value="1" id="page_data_0_d"
                                   name="active" <?php if ($vars['edit']['active'] == 1) echo ' checked="checked"'; ?>>
                            <label for="page_data_0_d">Вкл.</label>
                        </div>
                        <div class="select-field__item">
                            <input type="radio" class="select-field__radio" value="0" id="page_data_0_a"
                                   name="active" <?php if ($vars['edit']['active'] == 0) echo ' checked="checked"'; ?>>
                            <label for="page_data_0_a">Выкл.</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section__content section__content-w-50">
                <div class="section__title">SEO - секция</div>
                <div class="section__field">
                    <label>Title:</label>
                    <input type="text" class="form-control" value="<?php echo $vars['edit']['title'] ?>"
                           name="title"/>
                </div>
                <div class="section__field">
                    <label>Description:</label>
                    <textarea class="form-textarea form-textarea__h-120 no-size"
                              name="description"><?php echo $vars['edit']['description'] ?></textarea>
                </div>
            </div>
            <div class="section__content section__content-w-100">
            <div class="section__editor">
                <label>Описание:</label>
                <?php echo showEditor('body', $vars['edit']['body'])?>
            </div>
        </div>
        </div>
        <div class="tabs tabs-section-faq hidden">
            <div class="section__content section__content-w-100">
                <div class="info-faq">
                    <div class="info-faq__title">Для разделов каталога</div>
                    <div class="info-faq__item"><b>{{category}}</b> - выводить текущею категорию</div>
                    <div class="info-faq__item"><b>{{price_products}}</b> - выводит три последних товара с текуще категории (с ценой)</div>
                    <div class="info-faq__item"><b>{{low_products}}</b> - выводит три последних товара с текуще категории самых дешевых (с ценой)</div>
                    <div class="info-faq__item"><b>{{best_products}}</b> - выводит три последних товара с текуще категории с отметкой <b>Топ продаж</b> (с ценой)</div>
                    <div class="info-faq__item"><b>{{popular_products}}</b> - выводит три последних товара с текуще категории с ометкой <b>Рекомендуем</b> (с ценой)</div>
                    <div class="info-faq__item"><b>{{new_products}}</b> - выводит три последних товара с текуще категории с ометкой <b>Новинки</b> (с ценой)</div>
                </div>
                <div class="section__title">Вопрос - ответ</div>
                <?php foreach ($vars['faq_list'] as $row) { ?>
                    <div class="faq-meta faq-del-<?php echo $row['id']?>">
                        <div class="faq-meta__left">
                            <input type="hidden" class="meta_id" value="<?php echo $row['id']?>" name="meta_id[]">
                            <div class="section__field">
                                <label>Вопрос:</label>
                                <input type="text" class="form-control" value="<?php echo $row['quest'] ?>"
                                       id="page_page_title" name="quest[]"/>
                            </div>
                            <div class="section__field">
                                <label>Ответ:</label>
                                <textarea class="form-textarea form-textarea__h-120 no-size" id="page_meta_descr"
                                          name="ans[]"><?php echo $row['ans'] ?></textarea>
                            </div>
                        </div>
                        <div class="faq-meta__right">
                            <button class="btn-del-in del-faq-item">Удалить вопрос/ответ</button>
                        </div>
                    </div>

                <?php } ?>
                <div class="faq-result"></div>
                <div class="faq-ans">
                    <div class="action-add add-faq">
                        <svg>
                            <use xlink:href="/resource/administrator-cms/images/svg/svg-sprite.svg#plus"></use>
                        </svg>
                        <a>Создать</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="update">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="update_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>



