<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title">Просмотр заявки</div>
</div>
<div class="tool">
    <a class="tool__link"
       href="/<?php echo PathToTemplateAdmin . '/' . $vars['action'] ?>/delete/<?php echo $vars['edit']['id'] ?>">
        Удалить эту запись
    </a>
</div>
<div class="section">
    <form method="POST" name="update-form">
        <input type="hidden" value="<?php echo $vars['edit']['id'] ?>" name="id"/>
        <div class="section__content section__content-w-50">
            <div class="section__title">Общая информация</div>
            <div class="section__field">
                <label class="required">Статус заявки:<span>*</span></label>
                <select class="custom-select" name="status">
                    <?php foreach ($vars['status'] as $row) { ?>
                        <option value='<?php echo $row ?>' <?php echo ($row == $vars['edit']['status']) ? ' selected' : '' ?>><?php echo $row ?></option>
                    <?php } ?>
                </select>
            </div>
            <?php if (!empty($vars['edit']['from_p'])) { ?>
            <div class="section__field d-flex">
                <label>Какая форма:</label>
                <span><?php echo $vars['edit']['from_p'] ?></span>
            </div>
            <?php } ?>
            <?php if (!empty($vars['edit']['prod_id'])) {?>
                <div class="comment-prod">
                    <div class="comment-prod__photo">
                        <?php echo Links::getPhoto($vars['edit'])?>
                    </div>
                    <div class="comment-prod__right">
                        <div class="comment-prod__title"><?php echo $vars['edit']['prod_name']?></div>
                        <div class="comment-prod__link">
                            <a href="/product/<?php echo $vars['edit']['prod_link']?>" target="_blank">перейти к товару</a>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <?php if (!empty($vars['edit']['date'])) { ?>
            <div class="section__field d-flex">
                <label>Дата (редакт.):</label>
                <span><?php echo $vars['edit']['date'] ?></span>
            </div>
            <?php } ?>
            <?php if (!empty($vars['edit']['name'])) { ?>
            <div class="section__field d-flex">
                <label>Имя:</label>
                <span><?php echo $vars['edit']['name'] ?></span>
            </div>
            <?php } ?>
            <?php if (!empty($vars['edit']['phone'])) { ?>
            <div class="section__field d-flex">
                <label>Телефон:</label>
                <span><?php echo $vars['edit']['phone'] ?></span>
            </div>
            <?php } ?>
            <?php if (!empty($vars['edit']['email'])) { ?>
            <div class="section__field d-flex">
                <label>Почта:</label>
                <span><?php echo $vars['edit']['email'] ?></span>
            </div>
            <?php } ?>
            <?php if (!empty($vars['edit']['text'])) { ?>
            <div class="section__field d-flex">
                <label>Текст:</label>
                <span><?php echo $vars['edit']['text'] ?></span>
            </div>
            <?php } ?>
        </div>

        <div class="button-list-in">
            <div class="btn-save">
                <input type="submit" value="Сохранить" name="update">
            </div>
            <div class="btn-save-close">
                <input type="submit" value="Сохранить и закрыть" name="update_close">
            </div>
        </div>
        <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
    </form>
</div>
