<?php echo $vars['message'] ?>
<div class="main__top d-flex justify-content-space-between align-items-center">
    <div class="main__title"><?php echo $vars['name'] ?></div>
</div>
<div class="main__content">
    <div class="main__left">
        <div class="main-section">
            <form name="user-list" method="post"
                  action="/<?php echo PathToTemplateAdmin ?>/<?php echo $vars['action'] ?>/update">
                <?php echo $vars['list']; ?>
                <input type="hidden" value="<?php echo $vars['action'] ?>" id="action"/>
                <div class="button-list">
                    <div class="btn-del">
                        <input type="submit" value="Удалить выбранные" name="delete">
                    </div>
                </div>
            </form>
        </div>
    </div>

