<table class="table">
    <thead>
    <tr>
        <th width="30">
            <input type="checkbox"
                   id="customCheckAll"
                   title="Отметить/снять все"
                   value="Y"
                   name="id[]" class="custom-control-label-all">
            <label for="customCheckAll"></label>
        </th>
        <th width="50">ID</th>
        <th>Дата</th>
        <th>Имя</th>
        <th>Телефон</th>
        <th>Статус</th>
        <th width="160">Действие</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($vars['list'] as $row) {
        $new_status = '';
        if ($row['status'] == 'новая')
            $new_status = 'class="new-status"';
        ?>
        <tr <?php echo $new_status?>>
            <td>
                <input type="checkbox" value="<?php echo $row['id'] ?>"
                       id="customCheck<?php echo $row['id'] ?>"
                       name="id[]" class="custom-control-label">
                <label for="customCheck<?php echo $row['id'] ?>"></label>
            </td>
            <td><?php echo $row['id'] ?></td>
            <td><?php echo $row['date'] ?></td>
            <td><?php echo $row['name'] ?></td>
            <td><?php echo $row['phone'] ?></td>
            <td><?php echo $row['status'] ?></td>
            <td class="d-flex justify-content-between align-items-center h-65">
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/edit/' . $row['id']) ?>"
                   class="tool-show">Просмотр</a>
                <a href="<?php echo Links::getAdminURl(PathToTemplateAdmin . '/' . $vars['action'] . '/delete/' . $row['id']) ?>"
                   class="tool-del">Удалить</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php echo $vars['paging'] ?>