<div class="title-text">
    <div class="container">
        <div class="title-text__title" data-aos="type1" data-aos-duration="1400">
            <h1><?php echo $vars['constructor']['content_page_res'][$content['id']]['title']['value'] ?></h1>
        </div>
        <div class="title-text__text" data-aos="type1" data-aos-duration="1400" data-aos-delay="200">
            <?php echo htmlspecialchars_decode($vars['constructor']['content_page_res_text'][$content['id']]['text']['value']) ?>
        </div>
    </div>
</div>